%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

SerialNumber: "00G88325507"
CameraName: "left"
TopicName: "left_camera/image"
# Exposure Auto, 0 stands for Off, 1 stands for Once, 2 stands for Continues
ExposureAuto: 2
AutoExposureTimeLower: 65
AutoExposureTimeUpper: 10000
# Gain Auto, 0 stands for Off, 1 stands for Once, 2 stands for Continues
GainAuto: 2
Gain: 12.1  # min: 0   max: 17.0166
ExposureTime: 10000 # min: 15  max: 9999500
# Gamma Selector, 0 stands for user, 1 stands for sRGB
GammaSelector: 1


